version: "3.8"

volumes:
  postgresdata:

services:
  db:
    image: postgres:15-alpine
    container_name: booking_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - 7777:5432

  redis:
    image: redis:7-alpine
    container_name: booking_redis

  booking:
    build: ./
    container_name: booking_app
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    command: [ "/booking/docker/app.sh" ]
    ports:
      - 8000:8000

  celery:
    build: ./
    container_name: booking_celery
    command: [ "/booking/docker/celery.sh", "celery" ]
    env_file:
      - .env.prod
    depends_on:
      - redis

  flower:
    build: ./
    container_name: booking_flower
    command: [ "/booking/docker/celery.sh", "flower" ]
    env_file:
      - .env.prod
    depends_on:
      - redis
    ports:
      - 5555:5555